export { default as Resume} from './resume/resume'
export { default as Homepage} from './homepage/homepage'
export { default as About} from './about/about'
export { default as Portfolio} from './folio/folio'
export { default as Blog} from './blog/blog'
export { default as Contact} from './contact/contact'
